CREATE TABLE  "CLIENTES" 
   (	"ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TELEFONE" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("TELEFONE")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "CLIENTES_PF" 
   (	"ID" NUMBER(*,0), 
	"CPF" VARCHAR2(14) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SOBRENOME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("NOME", "SOBRENOME")
  USING INDEX  ENABLE, 
	 UNIQUE ("CPF")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "CLIENTES_PJ" 
   (	"ID" NUMBER(*,0), 
	"RAZAO_SOCIAL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CNPJ" VARCHAR2(18) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CNPJ")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "COMPRAS" 
   (	"ID" NUMBER(*,0), 
	"DATA" TIMESTAMP (6) NOT NULL ENABLE, 
	"VALOR" NUMBER(*,0) NOT NULL ENABLE, 
	"FUNCIONARIOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FORNECEDORES_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("DATA", "FUNCIONARIOS_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "COMPRAS_PRODUTOS" 
   (	"QUANTIDADE" NUMBER(*,0) NOT NULL ENABLE, 
	"COMPRAS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUTOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "COMPRAS_PRODUTOS_UK" UNIQUE ("PRODUTOS_ID", "COMPRAS_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "FORNECEDORES" 
   (	"ID" NUMBER(*,0), 
	"CNPJ" VARCHAR2(18) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RAZAO_SOCIAL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOME_FANTASIA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CNPJ")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "FUNCIONARIOS" 
   (	"ID" NUMBER(*,0), 
	"MATRICULA" NUMBER(*,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SOBRENOME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CPF" VARCHAR2(14) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FUNCAO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("MATRICULA")
  USING INDEX  ENABLE, 
	 UNIQUE ("NOME", "SOBRENOME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CPF_UK" UNIQUE ("CPF")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "ITENS" 
   (	"QUANTIDADE" NUMBER(*,0) NOT NULL ENABLE, 
	"SERVICOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUTOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ITENS_UK" UNIQUE ("PRODUTOS_ID", "SERVICOS_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "PRODUTOS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ITEM" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MARCA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CATEGORIA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("MARCA", "ITEM")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "SERVICOS" 
   (	"ID" NUMBER(*,0), 
	"DATA" TIMESTAMP (6) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(32) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TIPO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DURACAO" VARCHAR2(32) COLLATE "USING_NLS_COMP", 
	"VALOR" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCONTO" NUMBER(*,0), 
	"AVALIACAO" NUMBER(*,0), 
	"VISTORIAS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("DATA", "VISTORIAS_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "TAREFAS" 
   (	"FUNCIONARIOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SERVICOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "TAREFAS_UK" UNIQUE ("FUNCIONARIOS_ID", "SERVICOS_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "VEICULOS" 
   (	"ID" NUMBER(*,0), 
	"PLACA" VARCHAR2(8) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MARCA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"MODELO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"VERSAO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"KM" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTES_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PLACA")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "VISTORIAS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDEM_SERVICO" NUMBER(*,0) NOT NULL ENABLE, 
	"DATA" TIMESTAMP (6) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"VEICULOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FUNCIONARIOS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ORDEM_SERVICO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
ALTER TABLE  "VISTORIAS" ADD CONSTRAINT "FK_VEICULOS" FOREIGN KEY ("VEICULOS_ID")
	  REFERENCES  "VEICULOS" ("ID") ENABLE
/
ALTER TABLE  "VISTORIAS" ADD CONSTRAINT "FK_FUNCIONARIOS" FOREIGN KEY ("FUNCIONARIOS_ID")
	  REFERENCES  "FUNCIONARIOS" ("ID") ENABLE
/
ALTER TABLE  "TAREFAS" ADD FOREIGN KEY ("FUNCIONARIOS_ID")
	  REFERENCES  "FUNCIONARIOS" ("ID") ENABLE
/
ALTER TABLE  "TAREFAS" ADD FOREIGN KEY ("SERVICOS_ID")
	  REFERENCES  "SERVICOS" ("ID") ENABLE
/
ALTER TABLE  "CLIENTES_PF" ADD FOREIGN KEY ("ID")
	  REFERENCES  "CLIENTES" ("ID") ENABLE
/
ALTER TABLE  "CLIENTES_PJ" ADD FOREIGN KEY ("ID")
	  REFERENCES  "CLIENTES" ("ID") ENABLE
/
ALTER TABLE  "COMPRAS" ADD FOREIGN KEY ("FUNCIONARIOS_ID")
	  REFERENCES  "FUNCIONARIOS" ("ID") ENABLE
/
ALTER TABLE  "COMPRAS" ADD CONSTRAINT "FK_FORNECEDORES" FOREIGN KEY ("FORNECEDORES_ID")
	  REFERENCES  "FORNECEDORES" ("ID") ENABLE
/
ALTER TABLE  "ITENS" ADD FOREIGN KEY ("SERVICOS_ID")
	  REFERENCES  "SERVICOS" ("ID") ENABLE
/
ALTER TABLE  "VEICULOS" ADD FOREIGN KEY ("CLIENTES_ID")
	  REFERENCES  "CLIENTES" ("ID") ENABLE
/
ALTER TABLE  "SERVICOS" ADD FOREIGN KEY ("VISTORIAS_ID")
	  REFERENCES  "VISTORIAS" ("ID") ENABLE
/
ALTER TABLE  "ITENS" ADD CONSTRAINT "PRODUTOS_FK" FOREIGN KEY ("PRODUTOS_ID")
	  REFERENCES  "PRODUTOS" ("ID") ENABLE
/
ALTER TABLE  "COMPRAS_PRODUTOS" ADD CONSTRAINT "COMPRAS_FK" FOREIGN KEY ("COMPRAS_ID")
	  REFERENCES  "COMPRAS" ("ID") ENABLE
/
ALTER TABLE  "COMPRAS_PRODUTOS" ADD CONSTRAINT "COMPRAS_PRODUTOS_FK" FOREIGN KEY ("PRODUTOS_ID")
	  REFERENCES  "PRODUTOS" ("ID") ENABLE
/
CREATE OR REPLACE EDITIONABLE SYNONYM  "DBMS_XPLAN" FOR "LIVESQL"."ORACLE_SQL_USER_XPLAN"
/
CREATE OR REPLACE EDITIONABLE SYNONYM  "V$SESSION" FOR "LIVESQL"."ORACLE_SQL_USER_V$SESSION"
/
CREATE OR REPLACE EDITIONABLE SYNONYM  "V$SQL_PLAN_STATISTICS_ALL" FOR "LIVESQL"."ORACLE_SQL_USER_V$SQL_PLAN_S_A"
/